### ISSUE TITLE
Deployment Log Link Obfuscated

### ISSUE THREAD

**Issue by raahmed** [Azure/appservice-settings#16]
In the webapps-deploy@v2 log output, the link to the deployment logs is obfuscated since GHA thinks it’s a secret. Can you help us address this? Is there some way we can hint to GHA that the hyperlink is not a secret?

![image](https://user-images.githubusercontent.com/25991359/97607479-42d2ca00-19ce-11eb-870f-07ee1e11f65a.png)

![image](https://user-images.githubusercontent.com/25991359/97607490-46fee780-19ce-11eb-8b8d-1b3c005f609f.png)

**Comment by aksm-ms** [comment]
@raahmed I have added a new input "mask-inputs" in [action.yml](https://github.com/Azure/appservice-settings/blob/master/action.yml#L20). Please set this to "false" if you don't want your inputs to be masked in further actions.
Please note, if mask-inputs is set as false, all the input jsons and its individual values will not be set as secret.
For further reference and sample workflow, please refer [README](https://github.com/Azure/appservice-settings/blob/master/README.md#configure-github-secrets-with-azure-credentials-app-settings-and-connection-strings)

**Comment by aksm-ms** [comment]
@raahmed Please use this feature and let me know if it works.

**Comment by aksm-ms** [comment]
@raahmed Please check this on your side and let me know.

**Comment by aksm-ms** [comment]
Closing the issue since we have fixed it in PR. Please feel free to open if you face any issues.

**Comment by qubitron** [comment]
Hi @aksm-ms , I am still seeing my logs obfuscated in my deployment in github actions. Are there any changes I need to make to get this fix?
